Features/contacts
Serhii-Pushok/icecream pull request #23
Opened 2022-08-13 10:26 UTC by ostappatalakh

First request
Make all @media for main items.

2022-08-13 13:17 UTC, Serhii-Pushok requested changes

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/main.scss
> +@import './components/contacts';
Тут вже конфлікт, потрібно виправити

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours weekday">06:00 AM - 10:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours">08:00 AM - 16:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours weekday">06:00 AM - 10:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours">08:00 AM - 16:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours weekday">06:00 AM - 10:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/partials/contacts.html
> +                        <p class="contacts__item__working-hours-hours">08:00 AM - 16:00 PM</p>
Для семантики краще використовувати тег < time >

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +p {
краще не використовувати в якості селектору тег

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +    width: 320px;
Зверни увагу я вже давав для селектора .container властивості (в бейзі). Тобі повторно прописувати одні і ті ж властивості не потрібно

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +    }
медіаправила для контейнера я також додавав

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        var(--secondary-bcg-color) 23%);
якщо в тебе на 772 (хоча в нас такого брекпоінту немає) такий же градієнт як і на 320, то його не портібно прописувати. Уже коли відбуваються зміни (1200рх), тоді і прописуємо

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        outline: 1px solid tomato;
думаю він тут лишній

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +    &__buttons .contacts__button + .contacts__button {
Якщо я не помиляюсь, то плюсувати селектори - це не по методології Бєму. Краще прописувати з nth-child

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +        @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +    @media (min-width: 772px) {
такого прекпоінту немає. Вірно 768

2022-08-13 13:17 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +.button {
пропиши поки назву селектору унікально для своєї секції. Коли будемо ініфіковувати кнопки, то змінемо (якщо буде час). Щоб не злетіли кнопки в інших

2022-08-14 10:05 UTC, ostappatalakh commented on src/sass/components/_contacts.scss
> +p {
то скинь його у reset.

2022-08-14 10:06 UTC, ostappatalakh commented on src/sass/components/_contacts.scss
> +        outline: 1px solid tomato;
вірно, для себе робив - не прибрав.

2022-08-14 10:06 UTC, ostappatalakh commented on src/sass/components/_contacts.scss
> +    width: 320px;
дублюючі прибрав

2022-08-14 14:50 UTC, Serhii-Pushok approved these changes

2022-08-14 14:50 UTC, Serhii-Pushok commented on src/sass/components/_contacts.scss
> +p {
ок, залишай як є

2022-08-14 14:50 UTC, merged