add fixes
Serhii-Pushok/icecream pull request #27
Opened 2022-08-13 17:45 UTC by YuliaOd

2022-08-13 21:16 UTC, Serhii-Pushok requested changes

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    @media screen and (max-width: 320px) {
Цей рядок видаляємо повністю. Залишаємо для селектора .advantages властивість padding-top: 40px; з 4 рядка

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +
додаємо медіа правило @media screen and (min-width: 768px) {
     padding-bottom: 64px;
            }

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +            }
ось це медіаправило (рядок 7-9) видаляй

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +      <h1 class="visually-hidden">advantages</h1>
тут заголовок < h2>

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          src="./images/advantages/721.png" alt="milk" width="50" />
Рядок 6-7 видаляй. У нас по тз іконки переваг у макеті відображені у форматі png. У верстці їх необхідно реалізувати псевдоелементами. Тобто ми всі елементи реалізовуємо через псевдоелемент before.

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <h2 class="advantages__title">721</h2>
Це заголовок h3. Додай окремий клас < li class="advantages__title (тут якась назва класу долдаткового унікального)" > Тобі це потрібно буде для того, щоб розмістити картинки перед цими заголовками

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          src="./images/advantages/16.png" alt="apple" width="50" />
Рядок 12-13 видаляй. У нас по тз іконки переваг у макеті відображені у форматі png. У верстці їх необхідно реалізувати псевдоелементами. Тобто ми всі елементи реалізовуємо через псевдоелемент before.

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <h2  class="advantages__title">16kg</h2>
це заголовок h3. Додай окремий клас < li class="advantages__title (тут якась назва класу долдаткового унікального - не схожого з рядком 8)" > Тобі це потрібно буде для того, щоб розмістити картинки перед цими заголовками

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          src="./images/advantages/84.png" alt="ice cream" width="44" />
Рядок 19-20 видаляй. У нас по тз іконки переваг у макеті відображені у форматі png. У верстці їх необхідно реалізувати псевдоелементами. Тобто ми всі елементи реалізовуємо через псевдоелемент before.

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +            <h2  class="advantages__title">84</h2>
це заголовок h3. Додай окремий клас < li class="advantages__title (тут якась назва класу долдаткового унікального - не схожого з рядком 8 та рядком 14)" > Тобі це потрібно буде для того, щоб розмістити картинки перед цими заголовками

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    text-transform: lowercase;
text-transform: uppercase;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    margin: 0;
margin-bottom: 13px;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    @media screen and (max-width: 767px) {
@media screen and (min-width: 768px)

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    line-height: 1.14;
додати font-size: 36px;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        font-size: 36px;
font-size: 48px;
line-height: 1.15;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-top: 16px;
це прибирай

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +            }
рядки 25-29 прибирай

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-top: 40px;
Додавай line-height: 1.14;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        margin: 0;
margin-bottom: 16 px;

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    }
.(якась назва класу долдаткового унікального, яку ти пропишеш в рядку 8)::after {
        content: '';
        position: absolute;
        top: 16px;
        left: 0;
        width: 33px;
        height: 50px;
        background-image:  url(шлях до картинки 1);
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
}

@media (min-device-pixel-ratio: 2),
(min-resolution: 192dpi),
(min-resolution: 2dppx) ... далі запитаєш у Олени Педко (вона знає як це зробити, дуже багато коду писати)

2022-08-13 21:16 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    @media screen and (min-width: 768px) {
З усім останнім я попросив Олену тобі допомогти завтра. Завтра вже доробите

2022-08-14 11:08 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +
+

2022-08-14 11:08 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    @media screen and (max-width: 320px) {
+

2022-08-14 11:09 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +            }
+

2022-08-14 11:09 UTC, YuliaOd commented on src/partials/advantages.html
> +      <h1 class="visually-hidden">advantages</h1>
+

2022-08-14 11:11 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +            }
+

2022-08-14 11:11 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-top: 40px;
+

2022-08-14 11:12 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        margin: 0;
+

2022-08-14 14:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    @media screen and (max-width: 320px) {
+

2022-08-14 14:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +
+

2022-08-14 14:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +            }
+

2022-08-14 14:34 UTC, YuliaOd commented on src/partials/advantages.html
> +      <h1 class="visually-hidden">advantages</h1>
+

2022-08-14 14:35 UTC, YuliaOd commented on src/partials/advantages.html
> +          src="./images/advantages/721.png" alt="milk" width="50" />
+

2022-08-14 14:36 UTC, YuliaOd commented on src/partials/advantages.html
> +          src="./images/advantages/16.png" alt="apple" width="50" />
+

2022-08-14 14:36 UTC, YuliaOd commented on src/partials/advantages.html
> +          src="./images/advantages/84.png" alt="ice cream" width="44" />
+

2022-08-14 14:36 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    text-transform: lowercase;
+

2022-08-14 14:37 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    margin: 0;
+

2022-08-14 14:38 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    @media screen and (max-width: 767px) {
+

2022-08-14 14:40 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        font-size: 36px;
+

2022-08-14 14:40 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-top: 16px;
+

2022-08-14 14:41 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +            }
+

2022-08-14 14:41 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-top: 40px;
+

2022-08-14 14:41 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        margin: 0;
+

2022-08-14 20:00 UTC, Serhii-Pushok requested changes

2022-08-14 20:00 UTC, Serhii-Pushok commented on src/sass/main.scss
> +@import './components/advantages';
тут конфлікт, потрібно виправити

2022-08-14 20:00 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +// .advantages {
коментарі видаляй

2022-08-14 20:17 UTC, Serhii-Pushok approved these changes

2022-08-14 20:17 UTC, merged