Gallery 1 commit Day 1st
Serhii-Pushok/icecream pull request #3
Opened 2022-08-11 16:28 UTC by Lovchinskaya

2022-08-11 22:06 UTC, Serhii-Pushok requested changes

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/index.html
> +      <!-- <include src="./partials/example.html"></include> -->
Це можна прибирати

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +    background-color: greenyellow;
використовуємо змінні

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +    border: 4px solid darkgreen;
також змінні використовуємо

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +    height: 136px;
ти впевнена, що потрібно фіксовану висоту ставити?

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +    height: 327px;
аналогічно

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +        height: 430px;
аналогічно

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +        background-color: palevioletred;
змінні

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +        border: 2px solid red;
змінні

2022-08-11 22:06 UTC, Serhii-Pushok commented on src/sass/components/_gallery.scss
> +        }
Я взагалі щось не уявляю як це буде працювати))

2022-08-12 04:31 UTC, Lovchinskaya commented on src/index.html
> +      <!-- <include src="./partials/example.html"></include> -->
Це я маю прибирати із індекса?

2022-08-12 04:33 UTC, Lovchinskaya commented on src/index.html
> +      <!-- <include src="./partials/example.html"></include> -->
Всі інші коментариі ти зробив дарма, бо це скілет, каркас, і всього то, там кольори різнобарвні, для того щоб я бачила для себе респонсивність і розташування, коли заповню контентом я все приберу)))

2022-08-12 05:46 UTC, Serhii-Pushok approved these changes

2022-08-12 05:47 UTC, Serhii-Pushok commented on src/index.html
> +      <!-- <include src="./partials/example.html"></include> -->
добре

2022-08-12 05:47 UTC, merged