Concats modal
Serhii-Pushok/icecream pull request #51
Opened 2022-08-14 21:49 UTC by ostappatalakh

Make for all devices. 
Tommorow I'll try to make tabs

2022-08-14 22:11 UTC, Serhii-Pushok requested changes

2022-08-14 22:11 UTC, Serhii-Pushok commented on css/main.css
> +@charset "UTF-8";
включив Watch Sass і пішло підятгування css

2022-08-14 22:11 UTC, Serhii-Pushok commented on src/sass/main.scss
> +@import './components/contacts-modal';
тут конфлікт

2022-08-14 22:15 UTC, ostappatalakh commented on css/main.css
> +@charset "UTF-8";
я не включав.... все через термінал. Зараз подивлюсь. Але здається що вже завтра зможу розібратися...

2022-08-14 22:17 UTC, ostappatalakh commented on src/sass/main.scss
> +@import './components/contacts-modal';
може просто ти чиюсь гілку прийняв?

2022-08-15 15:00 UTC, Serhii-Pushok approved these changes

2022-08-15 15:00 UTC, merged