Feature/advantages
Serhii-Pushok/icecream pull request #9
Opened 2022-08-12 06:48 UTC by YuliaOd

Не підключилися стилі, Help

2022-08-12 10:05 UTC, Serhii-Pushok requested changes

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +<section class="advantages">
задай секції загальний клас - section (там вже він йде з падінгами). Якщо тобі потрібно перебити падінги, то просто новий клас створюєш. Клас - advantages - норм і ти просто до нього верхні/нижні падінги додавай, які не збігаються з основною секцією

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +      <h1 class="invisible-advantages">advantages</h1>
тут потрібно буде інший клас загальний вказати (я його створю - visually-hidden). щоб не повністю скривати загаловок, а робити його доступними для скрінрідерів

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +      <ul class="advantages-list">
Ми вирішили писати по методології БЄМ, тому краще написати назву класу advantages__list

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
По БЄМу advantages__item

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <h2 class="advantages-title">721</h2>
По БЄМу advantages__title

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
По БЄМу advantages__text

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <h2  class="advantages-title">16kg</h2>
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +           <h2  class="advantages-title">84</h2>
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
аналогічно

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages {
Не забувай про падінги на секцію

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.invisible-advantages{
Тут буде інший клас - visually-hidden. я його створю. Ти тільки його додай на заголовок

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    display: none;
прибираємо

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +font-style: normal;
якщо фонт-стайл - нормал, то його можна не вказувати, він за замовчкванням йде. Лишній код

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +line-height: 66px;
лайн-хейт ми скрізь пишемо не в пікселях, а у відношеннях. Для цього ми лайн-хейт в пікселях ділимо на фонт сайз. В цьому випадку так виходить 66/58=1.14 (заокруглюємо до сотих)

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +letter-spacing: 0.04em;
якщо в тебе леттер-спейсінг 0.04 ем, то він зазначений в _body.scss. Тому писати лишній раз непотрібно. Якщо ж інший, то звичайно прописуй

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    margin: 0;
Ми спочатку прописуємо стилі для мобілки, а вже потім за допомогою медіа правил пишемо для таблетки і десктопу. Тому спочатку пропиши стилі для мобілки, а вже потім для інших екранів

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages-title {
можна вкладенням прописати і не писати кожен раз назву класу. Якщо не знаєш як - то кажи, розкажу

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    margin: 0px;
ресетом ці стилі скинуті, їх не потрібно прописувати. Якщо якісь дописати потрібно, то звичайно додавай клас, однак якщо ти стандартні прописуєш стилі, то їх не потрібно зазначати

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +     width: 230px;}
Краще зазначити max-width

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-top: 32px;
краще робити марджинами

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        width: 180px;
краще max-width

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-right: 115px;
марджином

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-left: 80px;
марджином

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/main.css
> +}/*# sourceMappingURL=main.css.map */
всі css файли потрібно видалити. Вони загружаються, коли ти натискаєш Watch sass. Ми, крім роботи в терміналі нічого не робимо. Ні Watch sass, ні Live Server не натискаємо

2022-08-12 10:05 UTC, Serhii-Pushok commented on src/sass/main.scss
> +@import './components/advantages';
виправити конфлікт. Відос скинув, подивишся

2022-08-12 14:37 UTC, YuliaOd commented on src/partials/advantages.html
> +<section class="advantages">
+

2022-08-12 14:38 UTC, YuliaOd commented on src/partials/advantages.html
> +      <ul class="advantages-list">
+

2022-08-12 15:56 UTC, YuliaOd commented on src/partials/advantages.html
> +          <h2 class="advantages-title">721</h2>
+

2022-08-12 15:58 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-right: 115px;
+

2022-08-12 15:58 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-left: 80px;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +      <h1 class="invisible-advantages">advantages</h1>
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +font-style: normal;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +font-style: normal;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +line-height: 66px;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +letter-spacing: 0.04em;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        padding-top: 32px;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        width: 180px;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    margin: 0;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +          <h2  class="advantages-title">16kg</h2>
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +        <li class="advantages-list-item">
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +           <h2  class="advantages-title">84</h2>
+

2022-08-12 22:34 UTC, YuliaOd commented on src/partials/advantages.html
> +          <p class="advantages-text">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +.advantages {
про верхні та нижні падінги?

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +.invisible-advantages{
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    display: none;
+

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +.advantages-title {
Якщо не складно, розкажи як) можливо через &?

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +    margin: 0px;
Мается на увазі, радінги і маржини та none?

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/main.css
> +}/*# sourceMappingURL=main.css.map */
Не змогла знайти файли css

2022-08-12 22:34 UTC, YuliaOd commented on src/sass/main.scss
> +@import './components/advantages';
+

2022-08-13 07:06 UTC, Serhii-Pushok requested changes

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +<section>
перепрошую - залишай так як було section class="advantages"

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +            src="" alt="milk" width="50" />
в src вказуй шлях "./images/advantages/721.png"

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          src="" alt="apple" width="50" />
в src вказуй шлях "./images/advantages/16.png"

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          src="" alt="ice cream" width="44" />
в src вказуй шлях "./images/advantages/84.png"

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/partials/advantages.html
> +          <img srcset="./images/advantages/16.png 1x, ./images/advantages/16@2x.png  2x "
тут не ту картинку вставила

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> -}
це залишай як було

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
>  font-size: 58px;
цей фонт-сайз вказуй в медіа правилі до цього селектора 
@media screen and (min-width: 1200px) {
font-size: 58px;
    }

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
>  @media screen and (min-width: 768px) {
медіа правила вказуй в селекторі .advantages__title, що дозволить тобі кожен раз під медіа правилом не зазначати цей селектор

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__title {
цей селектор видаляй і прописуй медіа правило в селекторі .advantages__title, який ти вже вказала вище

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__title {
аналогічно

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
>  .advantages-text {
дивись коментар вище

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__text {
аналогічно. кожен раз не потрібно прописувати селектор

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__list {
аналогічно

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__list {
аналогічно

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +.advantages__item {
в тебе ж вже написано селектор цей же вище. Додавай властивість в селектор, що ти вже вказала вище

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +     width: 230px;}
а чого не макс-віз?

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    .advantages__item:not(:first-child) {
спочатку селектор, а до нього вже медіа правило. Не навпаки

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        padding-top: 32px;
а чого не марджин-топ?

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +        width: 180px;
ні, я мав на увазі - max-width: 180px;  (min-width: 768px) - правильно

2022-08-13 07:06 UTC, Serhii-Pushok commented on src/sass/components/_advantages.scss
> +    .advantages__item {
також - спочатку селектор, а потім медіа-правило

2022-08-13 11:59 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +        width: 180px;
+

2022-08-13 12:19 UTC, YuliaOd commented on src/partials/advantages.html
> +<section>
+

2022-08-13 12:22 UTC, YuliaOd commented on src/partials/advantages.html
> +            src="" alt="milk" width="50" />
+

2022-08-13 12:23 UTC, YuliaOd commented on src/partials/advantages.html
> +          src="" alt="apple" width="50" />
+

2022-08-13 12:24 UTC, YuliaOd commented on src/partials/advantages.html
> +          src="" alt="ice cream" width="44" />
+

2022-08-13 12:24 UTC, YuliaOd commented on src/partials/advantages.html
> +          <img srcset="./images/advantages/16.png 1x, ./images/advantages/16@2x.png  2x "
+

2022-08-13 12:24 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> -}
+

2022-08-13 12:24 UTC, YuliaOd commented on src/sass/components/_advantages.scss
>  font-size: 58px;
+

2022-08-13 12:26 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +.advantages__title {
+

2022-08-13 12:26 UTC, YuliaOd commented on src/sass/components/_advantages.scss
> +.advantages__title {
+

2022-08-17 14:06 UTC, closed without merging